# Generated by Django 3.1.2 on 2020-11-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201110_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='f_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='l_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
