# Generated by Django 3.1.2 on 2020-11-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201110_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(default='97214', max_length=10),
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('temperment', models.CharField(blank=True, max_length=50, null=True)),
                ('crate_trained', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
