# Generated by Django 3.1.2 on 2020-11-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201110_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Portland', max_length=50),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='crate_trained',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
