# Generated by Django 3.1.2 on 2020-11-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201110_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_pupps',
            field=models.BooleanField(default=False),
        ),
    ]
