# Generated by Django 3.1.2 on 2020-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dog_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200)),
                ('dog_detail', models.CharField(max_length=500)),
                ('appt_time', models.DateTimeField(blank=True, null=True)),
                ('dog_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawsapp.customer')),
            ],
        ),
    ]
