# Generated by Django 3.1.2 on 2020-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0003_auto_20201023_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=50),
        ),
    ]
