# Generated by Django 3.1.2 on 2020-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0004_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='97214', max_length=10),
        ),
    ]
