# Generated by Django 3.1.2 on 2020-11-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
