# Generated by Django 3.1.2 on 2020-11-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0009_auto_20201116_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='puppy_train',
            new_name='puppy_training',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_dog',
        ),
    ]
