# Generated by Django 3.1.2 on 2020-11-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0011_appointment_appt_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_dog',
        ),
    ]
