# Generated by Django 3.1.2 on 2020-12-01 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0014_auto_20201130_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2020, 12, 1, 3, 13, 49, 64851, tzinfo=utc), max_length=100),
        ),
    ]
