# Generated by Django 3.1.2 on 2020-12-01 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0015_auto_20201130_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2020, 12, 1, 3, 16, 22, 438596, tzinfo=utc), max_length=100),
        ),
    ]
