# Generated by Django 3.1.2 on 2021-01-20 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0016_auto_20201130_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 1, 20, 13, 50, 15, 199124, tzinfo=utc), max_length=100),
        ),
    ]
