# Generated by Django 3.1.2 on 2021-01-20 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawsapp', '0017_auto_20210120_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 1, 20, 14, 15, 29, 483046, tzinfo=utc), max_length=100),
        ),
    ]
